version: '3'
services:

    #PHP Service
    polygon_app:
        build:
            context: ./.docker/php/8.0
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: polygon_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    polygon_webserver:
        image: nginx:alpine
        container_name: polygon_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    #MySQL Service
    polygon_db:
        image: mysql:5.7.22
        container_name: polygon_db
        restart: always
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ${PWD}/mysql:/var/lib/mysql
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - polygon_db
        environment:
            PMA_HOST: polygon_db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PASSWORD: root
        restart: always
        ports:
            - 8081:80
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
